package ports

import (
	"context"

	"github.com/Unikyri/gemini-live-agent-klyra/backend/internal/core/domain"
)

// AuthStrategy defines the contract for authentication strategies.
// Each authentication provider (Google, Guest, Email/Password) implements this interface.
//
// This follows the Strategy Pattern: the "what" (authentication flow) stays the same,
// but the "how" (credential validation) varies by provider.
//
// Example implementations:
// - GoogleAuthStrategy: Validates Google ID Token, extracts user claims
// - GuestAuthStrategy: Accepts client-provided email/name without validation (dev-only)
// - EmailPasswordStrategy: Validates email/password against stored hash (future)
type AuthStrategy interface {
	// Authenticate validates provider-specific credentials and returns a
	// provisional AuthResult containing provider + user identity data.
	//
	// Tokens are generated by the AuthUseCase to keep token policy centralized.
	//
	// The credentials map structure varies by provider:
	// - Google: {"id_token": "eyJhbGc..."}
	// - Guest: {"email": "test@example.com", "name": "Test User"}
	//
	// Returns:
	// - *domain.AuthResult: Contains provider and user identity (tokens may be empty)
	// - error: If credentials are invalid or validation fails
	//
	// Context should be respected for timeout/cancellation propagation.
	Authenticate(ctx context.Context, credentials domain.AuthCredentials) (*domain.AuthResult, error)
}
